version: '2'
services:
  mongo:
    image: "mongo:3"
  elasticsearch:
    image: "elasticsearch:2"
    command: "elasticsearch -Des.cluster.name='graylog'"
  graylog:
    image: graylog2/server:2.1.0-3
    environment:
      GRAYLOG_PASSWORD_SECRET: t3censust3census
      GRAYLOG_ROOT_PASSWORD_SHA2: a5564533fab3922177d894887d5d299a42532dfc9340c1b8b797a5fdda3613d1
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - "9000:9000"
      - "5555/udp:5555/udp"
      - "12201/udp:12201/udp"
      - "12202/udp:12202/udp"
